data:
  data_dir: datasets/eval/MVSEC/
  eye: left
  num_bins: 2
  undistort: true
  undistort_dir: datasets/map/
experiment: Default
hot_filter:
  enabled: true
  max_px: 100
  max_rate: 0.8
  min_obvs: 5
loader:
  augment: []
  batch_size: 1
  gpu: 0
  resolution:
  - 256
  - 256
  seed: 0
loss:
  clip_grad: 100.0
  flow_regul_weight: 0.001
  overwrite_intermediate: false
metrics:
  flow_scaling: 128
  name:
  - AEE
  - FWL
  - RSAT
model:
  activations:
  - arctanspike
  - arctanspike
  base_num_channels: 32
  encoding: cnt
  kernel_size: 3
  mask_output: true
  name: XLIFRecEVFlowNet
  norm_input: false
  num_bins: 2
  round_encoding: false
  spiking_neuron: None
spiking_neuron: {}
vis:
  activity: false
  bars: true
  delay: 1
  enabled: true
  px: 400
  store: false
