data:
    data_dir: datasets/test
    eye: "both"        # 可选：left/right/both
    num_bins: 2       # 体素编码的bin数
    undistort: True  # 是否去畸变
    undistort_dir: "datasets/map/" # 去畸变后的数据存放路径
model:
    name: XLIFRecEVFlowNet # 从model.py中导入的模型名称
    encoding: cnt # voxel;cnt，同上
    round_encoding: False # for voxel encoding
    norm_input: False # normalize input
    num_bins: 2
    base_num_channels: 32
    kernel_size: 3
    activations: [arctanspike, arctanspike] # activations for ff and rec neurons
    mask_output: True
    spiking_neuron: None
        #leak: [-4.0, 0.1] # 用ALIF或XLIF，PLIF时，需要使用leak_v和leak_t两个参数
        #thresh: [0.8, 0.1]
        #learn_leak: True
        #learn_thresh: True
        #hard_reset: True
segmentation:
    flow_threshold: 0.01
cluster:
    eps: 10
    min_samples: 3
match:
    stereo_matching: True # 是否使用双目匹配
    max_dist: 2 # 双目匹配的最大距离
    max_dt: 0.001 # 双目匹配的最大时间差
camera:
#按分辨率缩放了，从346,260到256,256
    fx: 167.495  # 226.38018519795807
    fy: 222.671  # 226.15002947047415
    cx: 128.479  #173.6470807871759
    cy: 131.676  #133.73271487507847
    baseline: 0.09988137641750752        # 米

metrics:
    name: [AEE, FWL, RSAT]  # FWL, RSAT, AEE
    flow_scaling: 128 # depends on the training dataset

loss:
    flow_regul_weight: 0.001
    clip_grad: 100.0 # set to Null to disable
    overwrite_intermediate: False

loader:
    batch_size: 1
    resolution: [256, 256] # H x W
    augment: []
    gpu: 0

vis:
    enabled: False
    px: 400
    delay: 1
    bars: True
    activity: True
    store: False

hot_filter:
    enabled: True
    max_px: 100
    min_obvs: 5
    max_rate: 0.8