data:
    data_dir: datasets/test/
    num_bins: 2       # 体素编码的bin数
model:
    name: PLIFRecEVFlowNet # for other models available, see models/model.py SpikingRecEVFlowNet XLIFRecEVFlowNet
    encoding: cnt # voxel;cnt，同上
    round_encoding: False # for voxel encoding
    norm_input: False # normalize input
    num_bins: 2
    base_num_channels: 32
    kernel_size: 3
    activations: [arctanspike, arctanspike] # activations for ff and rec neurons
    mask_output: True
    spiking_neuron: None
        #leak: [-4.0, 0.1]
        #thresh: [0.8, 0.1]
        #learn_leak: True
        #learn_thresh: True
        #hard_reset: True

metrics:
    name: [FWL, RSAT]  # FWL, RSAT, AEE
    flow_scaling: 128 # depends on the training dataset

loss:
    flow_regul_weight: 0.001
    clip_grad: 100.0 # set to Null to disable
    overwrite_intermediate: False

loader:
    batch_size: 1
    resolution: [256, 256] # H x W
    augment: []
    gpu: 0

vis:
    enabled: True
    px: 400
    delay: 1
    bars: True
    activity: False
    store: False

hot_filter:
    enabled: True
    max_px: 100
    min_obvs: 5
    max_rate: 0.8